name: Deploy Frontend ke cPanel

on:
  push:
    branches:
      - main  # Ubah ke 'master' jika branch utama Anda namanya master

jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Ambil Kode Terbaru
      uses: actions/checkout@v4

    - name: Siapkan Lingkungan Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24' # Sesuaikan dengan versi Node JS Anda

    - name: Install & Build
      run: |
        cd frontend
        npm install

        # --- MULAI MEMBUAT .ENV SEMENTARA ---
        touch .env
        echo "VITE_API_BASE_UR=${{ secrets.VITE_API_URL }}" >> .env
        echo "VITE_API_TIMEOUT=15000" >> .env
        # (Silakan tambahkan baris echo lain jika ada variabel tambahan)
        # --- SELESAI ---

        npm run build

    - name: Sinkronisasi FTP ke cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./frontend/dist/ 
        secure: true 